fix(tabs): Accessibility and keyboard interaction fixes
jeyoshimi/material pull request #1
Opened 2017-05-24 23:03 UTC by jeyoshimi

This commit does a few things related to accessibility:
1) Hides md-dummy-tabs completely from screen readers with aria-hidden.
With this change, screen readers do not hear the dummy tabs read out
when using linear navigation. Instead of focusing the dummy tabs, the
visible tabs are focused. There was a comment that mentions focusing the
dummy tabs as a way to avoid animation issues; however, I could not
replicate the mentioned issues.
2) Fixes the ARIA roles so users can hear "tab 1 of 3" instead of just
"tab" by moving role="tablist" to the direct parent element (which
contains the items marked role="tab").
3) Fixes keyboard interaction to match recommended ARIA practices by
focusing on the active tab when using TAB navigation, then resolving the
focus/active tab discrepancy on pressing TAB within the tablist.
4) Note that there is a SCSS change added in to retain current behavior
when the active tab is added to the tab order; however, this should
likely be reconsidered as it actively overrides default focus outline
behavior.

Closes #10075.

2017-05-25 18:33 UTC, slauriat requested changes

2017-05-25 18:33 UTC, slauriat commented on src/components/tabs/js/tabsController.js
> +   * This is used to forward focus to tab label elements.  This method is necessary to avoid
Focus moves to the tab container elements, not the label elements (label elements should never receive focus), just a comment nit.

2017-05-25 18:33 UTC, slauriat commented on src/components/tabs/js/tabsDirective.js
>                'aria-activedescendant="{{$mdTabsCtrl.getFocusedTabId()}}" ' +
This also needs to move down to the md-pagination-wrapper element, no? Or role="tablist" needs to stay on this one?

2017-05-25 22:06 UTC, jeyoshimi commented on src/components/tabs/js/tabsController.js
> +   * This is used to forward focus to tab label elements.  This method is necessary to avoid
Fixed!

2017-05-25 22:10 UTC, jeyoshimi commented on src/components/tabs/js/tabsDirective.js
>                'aria-activedescendant="{{$mdTabsCtrl.getFocusedTabId()}}" ' +
I think it gets straight up removed. From what I can gather on the aria practices page (https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel), "When the tab list is receiving focus, places focus on the active tab element . When the tab list contains the focus, moves focus to the next element in the page tab sequence outside the tablist, which is typically either the first focusable element inside the tab panel or the tab panel itself." I don't think the tablist element itself ever actually receives focus. (The example also has only the tab items receiving focus.)

2017-05-30 15:13 UTC, slauriat approved these changes

2017-05-30 20:21 UTC, merged